# Builds the Betaflight firmware
#
# After building, artifacts are released to a separate repository.

name: CI

on:
  push:
    branches:
      - master
      - '*-maintenance'
  pull_request:
    branches:
      - master
      - '*-maintenance'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-20.04
    outputs:
      targets: ${{ steps.get-targets.outputs.targets }}
    steps:
      - uses: actions/checkout@v2

      - name: Get all official build targets
        id: get-targets
        run: echo "::set-output name=targets::$(make targets-ci-print | jq -R -c 'split(" ")')"

      - name: Cache build toolchain
        uses: actions/cache@v2
        id: cache-toolchain
        with:
          path: tools/
          key: ${{ runner.os }}-${{ hashFiles('make/tools.mk') }}

      - name: Download and install toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make arm_sdk_install

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: ${{ fromJson(needs.setup.outputs.targets) }}
    steps:
      - uses: actions/checkout@v2

      - name: Fetch toolchain from cache
        uses: actions/cache@v2
        id: cache-toolchain
        with:
          path: tools/
          key: ${{ runner.os }}-${{ hashFiles('make/tools.mk') }}

      - name: Build target
        run: make EXTRA_FLAGS=-Werror ${{ matrix.target }}

      - name: Publish build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: obj/*.hex

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y libblocksruntime-dev

      - name: Run sanity checks
        run: make EXTRA_FLAGS=-Werror checks

      - name: Run all unit tests
        run: make EXTRA_FLAGS=-Werror test-all

  result:
    name: Complete
    needs: [build, test]
    if: ${{ always() }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check build matrix result
        if: ${{ needs.build.result != 'success' }}
        run: exit 1

      - name: Check test result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
